source :rubygems

# Server requirements
# gem 'thin' or mongrel

# Project requirements
gem 'rake'
gem 'rack-flash'

# Component requirements
gem 'bcrypt-ruby', :require => "bcrypt"
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'sass'
gem 'haml'
gem 'activerecord', :require => "active_record"
gem 'sqlite3'

# Test requirements
gem 'shoulda', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"


# Padrino
gem 'padrino', "0.9.29"
# Padrino EDGE
# gem 'padrino', :git => "git://github.com/padrino/padrino-framework.git"